apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chronogallery-upload-timeout
  namespace: default
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
  buffering:
    maxRequestBodyBytes: 10485760  # 10MB
    memRequestBodyBytes: 1048576   # 1MB
    maxResponseBodyBytes: 10485760 # 10MB
    memResponseBodyBytes: 1048576  # 1MB
    retryExpression: "IsNetworkError() && Attempts() < 3" 